### ISSUE TITLE
2fa Carshs c2

### ISSUE THREAD

**Issue by Crafttino21** [lolinekos/succubus#10]
If 2FA is enabled the user isnt able to connect to the net

**Comment by Crafttino21** [comment]
Just how i reportet you on Telegram. maybe its Timezone factore or Just Authy. Temporaly fix: connect over Windows SSH and speed copy the Code from the NET OTP

**Comment by 9xN** [comment]
learn2spellskid

**Comment by lolinekos** [comment]
make an assert for otp
