### ISSUE TITLE
Beware, this is malware!

### ISSUE THREAD

**Issue by DarkReaper231** [lolinekos/succubus#11]
First red flag is that there is no source code to `main` which should scare away most people here.
It's obfuscated with UPX to prevent detection. 
Now you can use upx to decompress the file using `upx -d main`
After that you are left with go compiled binary which seems to be heavily obfuscated too.
The code has been obfuscated by randomizing all strings and function names making it very difficult to reverse engineer.
After successful remapping of libraries and determining what's the actual code, it's still pretty hard to read.
However I am pretty sure it does something funky, first of all it sends some stuff to `succubus.neko.ltd`
There are also references to `https://succubus.neko.ltd/auth/succubus`, I couldn't figure out what it requires.
But anyway it's very suspicious and I wouldn't trust compiled binaries blatantly put into repositories anyway.

**Comment by lolinekos** [comment]
You do realized it's compiled to stop others from claiming my works, as well as to stop users who have not paid from getting access to paid content. If you were also competent at reverse engineering would have see the request it sends to the server. The request being a key, port, banner, and "trust string" used to validate the licensing server.

**Comment by DarkReaper231** [comment]
> You do realized it's compiled to stop others from claiming my works, as well as to stop users who have not paid from getting access to paid content. If you were also competent at reverse engineering would have see the request it sends to the server. The request being a key, port, banner, and "trust string" used to validate the licensing server.

"competent at reverse engineering", it's not exactly easy to reverse engineer stuff. Go compiles to machine code and doesn't leave much info to get good sense of what the code does. Plus you randomized all function names and strings so it's even harder to make sense of it all. Have you ever tried reverse engineering obfuscated go program? The fact I found anything at all is good enough for me.

**Comment by lolinekos** [comment]
I do not care about your friends. Why are you saying I am using upx for obfuscation when you said yourself "Now you can use upx to decompress the file". Also you seem to have gone from trying to call my code malware to trying to correct anything you can in an attempt to not look like the idiot you are.

**Comment by DarkReaper231** [comment]
> I do not care about your friends. Why are you saying I am using upx for obfuscation when you said yourself "Now you can use upx to decompress the file". Also you seem to have gone from trying to call my code malware to trying to correct anything you can in an attempt to not look like the idiot you are.

Whatever dude, you had your fair chance to defend your software. And I'm not correcting anything but putting compiled executables to repositories isn't exactly trustworthy behavior. Most malware on GotHub is just like that, they are repos with infected executable with some Readme but no source code. I stumbled on many of those. Why did you use upx in first place? It's not like it reduced filesize of your binary by much. And don't call me idiot. I at least don't `chmod 777`.

**Comment by 9xN** [comment]
lmao yes everyone with half  a brain cell knows this is probable malware but literally every single thing youve said especially the backtracking in the second comment makes you look like an even bigger moron

**Comment by DarkReaper231** [comment]
Whatever I'm gonna close the issue, I don't have enough evidence to tell if this is 100% malware and until learn reverse engineering properly, it's gonna stay that way.
