### ISSUE TITLE
Why Is it error when Is start ./main

### ISSUE THREAD

**Issue by hidhdhusnshsjsv** [lolinekos/succubus#12]
SUCCUBUS Build Version: Succubus Aquakuma v1.4.9
2023/11/15 23:49:46 Init() Loading Config
2023/11/15 23:49:47 Error: "invalid key" default succubus initiating.
2023/11/15 23:49:47 Init() Connected to database
2023/11/15 23:49:47 Database Error: "Error 1698 (28000): Access denied for user 'root'@'localhost'"

**Comment by lolinekos** [comment]
you need to make sure you have your database setup correctly and have attempted using the command on the readme to allow yourself to connect
