### ISSUE TITLE
Error oracle

### ISSUE THREAD

**Issue by Bani4kaa** [lolinekos/succubus#14]
ubuntu@n-3:~/succubus$ ./main
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault (core dumped)

**Comment by lolinekos** [comment]
it's compiled to x86 i think you may be using some other architecture

**Comment by irwj** [comment]
![image](https://github.com/lolinekos/succubus/assets/122724138/757375a3-6ece-4b25-bf38-cd9ed02e5f57)

**Comment by Bani4kaa** [comment]
Please help me!

**Comment by lolinekos** [comment]
you need to run the binary on the intended device or use an emulator which i have none to recommend
