### ISSUE TITLE
new things to add too succubus

### ISSUE THREAD

**Issue by fefegeggegre** [lolinekos/succubus#9]
Add TUI Options
Better api manager with more options
blacklist/whitelist to the api manager

**Comment by 2waysz** [comment]
nigr

**Comment by lolinekos** [comment]
What TUI options were you thinking?

**Comment by 9xN** [comment]
> What TUI options were you thinking?

making it not gay

**Comment by lolinekos** [comment]
> > What TUI options were you thinking?
> 
> making it not gay

not sure what you mean

**Comment by 9xN** [comment]
> > > What TUI options were you thinking?
> > 
> > 
> > making it not gay
> 
> not sure what you mean

make succubus find my dad
